/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2019-08-21 09:44:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import com.hcl.employ.DaoConnection;
import java.sql.Connection;

public final class UpdateEmploy_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("com.hcl.employ.DaoConnection");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

int empno=Integer.parseInt(request.getParameter("empno"));
Connection con=DaoConnection.getConnection();
String cmd="select *from employ where empno=?";
PreparedStatement pst=con.prepareStatement(cmd);
pst.setInt(1,empno);
ResultSet rs=pst.executeQuery();
rs.next();

      out.write("\r\n");
      out.write("<form method=\"get\" action=\"UpdateEmploy.jsp\">\r\n");
      out.write("\t\t<center>\r\n");
      out.write("\t\tEmploy No:\r\n");
      out.write("\t\t<input type=\"text\" name=\"empno\"\r\n");
      out.write("\t\treadonly=\"readonly\" value=");
      out.print(rs.getInt("empno") );
      out.write(" /><br/><br/>\r\n");
      out.write("\t\tEmploy Name:\r\n");
      out.write("\t\t<input type=\"text\" \r\n");
      out.write("\t\tvalue=");
      out.print(rs.getString("name") );
      out.write("\r\n");
      out.write("\t\tname=\"name\"/><br/><br/>\r\n");
      out.write("\t\tDepartment:\r\n");
      out.write("\t\t<input type=\"text\" \r\n");
      out.write("\t\tvalue=");
      out.print(rs.getString("dept") );
      out.write("\r\n");
      out.write("\t\tname=\"dept\"/><br/><br/>\r\n");
      out.write("\t\tDesignation:\r\n");
      out.write("\t\t<input type=\"text\" \r\n");
      out.write("\t\tvalue=");
      out.print(rs.getString("desig") );
      out.write("\r\n");
      out.write("\t\tname=\"desig\"/><br/><br/>\r\n");
      out.write("\t\tBasic:\r\n");
      out.write("\t\t<input type=\"text\" \r\n");
      out.write("\t\tvalue=");
      out.print(rs.getInt("basic") );
      out.write("\r\n");
      out.write("\t\tname=\"basic\"/><br/><br/>\r\n");
      out.write("\t\t<input type=\"submit\" value=\"update\"/><br/><br/>\r\n");
      out.write("\t\t</center>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t");

		if(request.getParameter("empno")!= null&& 
		request.getParameter("basic") !=null){
			cmd="update employ set name=?, dept=? , desig=? , basic=? "+
					" where empno=?";
		    pst =con.prepareStatement(cmd);
			pst.setString(1,request.getParameter("name"));
			pst.setString(2,request.getParameter("dept"));
			pst.setString(3,request.getParameter("desig"));
			pst.setInt(4,Integer.parseInt(request.getParameter("basic")));
			pst.setInt(5,empno);
			pst.executeUpdate();
			
      out.write("\r\n");
      out.write("\t\t\t");
      if (true) {
        _jspx_page_context.forward("EmployShow.jsp");
        return;
      }
      out.write("\r\n");
      out.write("\t\t");
 
		}
		
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
